name: Build Frontend

on:
  workflow_call:

jobs:
  lint_and_build_frontend:
    runs-on: ubuntu-latest
    container:
      image: node:23.1.0-alpine3.19

    steps:  
      - uses: actions/checkout@v5

      - name: Cache node_modules
        uses: actions/cache@v4
        id: npm-cache
        with:
            path: src/Client/node_modules
            key: node-modules-${{ hashFiles('src/Client/package-lock.json') }}

      - name: Install dependencies
        working-directory: ./src/Client
        run: |
            if [ -f package-lock.json ]; then
              npm ci
            else
              npm install --legacy-peer-deps
            fi
    
      - name: Run strict linter (no warnings allowed)
        working-directory: ./src/Client
        run: npx eslint src --ext .ts,.tsx,.js,.jsx --max-warnings=0

      - name: Build frontend
        working-directory: ./src/Client
        run: CI=false npm run build

  test_frontend:
    runs-on: ubuntu-latest
    needs: lint_and_build_frontend
    
    if: success() || (failure() && needs.lint_and_build_frontend.result == 'success')

    container:
      image: node:23.1.0-alpine3.19
    
    steps:
      - uses: actions/checkout@v5
      
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: src/Client/node_modules
          key: node-modules-${{ hashFiles('src/Client/package-lock.json') }}
      
      - name: Run tests
        working-directory: ./src/Client
        env:
          JEST_JUNIT_OUTPUT: junit.xml
        run: npx jest --coverage --testResultsProcessor=jest-junit
      
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage-${{ github.run_id }}
          path: src/Client/coverage/
          retention-days: 7
      
      - name: Upload junit report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-junit-${{ github.run_id }}-${{ github.run_attempt }}
          path: src/Client/junit.xml
          retention-days: 7