name: Pull Request CI

on:
  pull_request:

jobs:
  ci_backend:
    name: CI Backend
    uses: ./.github/workflows/ci_backend.yml

  ci_frontend:
    name: CI Frontend
    uses: ./.github/workflows/ci_frontend.yml