name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        description: "prod | test"
        required: true
        type: string
      branch:
        description: "Branch to deploy"
        required: true
        type: string
    secrets:
      SSH_HOST:
        required: true
      SSH_USER:
        required: true
      SSH_KEY:
        required: true
      GHCR_PAT:
        required: true

jobs:
  deploy_prod:
    if: ${{ inputs.environment == 'prod' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.branch }}

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add server to known_hosts
        run: ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Login to GHCR on server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "echo '${{ secrets.GHCR_PAT }}' | docker login ghcr.io -u gladcom --password-stdin"

      - name: Upload docker-compose
        run: |
          scp build/docker-compose.yaml \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:cifra/prod/docker-compose.yaml

      - name: Deploy PROD
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd cifra/prod &&
            PROJECT_NAME=prod \
            API_PORT=8000 \
            FRONT_PORT=7000 \
            PG_PORT=5540 \
            docker compose --project-name prod pull &&
            PROJECT_NAME=prod \
            API_PORT=8000 \
            FRONT_PORT=7000 \
            PG_PORT=5540 \
            docker compose --project-name prod up -d --remove-orphans
          "


  deploy_test:
    if: ${{ inputs.environment == 'test' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        stand:
          - { name: "test1", api: 8001, front: 7001, pg: 5541, dir: "test1" }
          - { name: "test2", api: 8002, front: 7002, pg: 5542, dir: "test2" }

    steps:
      - name: Checkout branch
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.branch }}

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add server to known_hosts
        run: ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Login to GHCR on server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "echo '${{ secrets.GHCR_PAT }}' | docker login ghcr.io -u gladcom --password-stdin"

      - name: Upload docker-compose for ${{ matrix.stand.name }}
        run: |
          scp build/docker-compose.yaml \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:cifra/${{ matrix.stand.dir }}/docker-compose.yaml

      - name: Deploy ${{ matrix.stand.name }}
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd cifra/${{ matrix.stand.dir }} &&
            PROJECT_NAME=${{ matrix.stand.name }} \
            API_PORT=${{ matrix.stand.api }} \
            FRONT_PORT=${{ matrix.stand.front }} \
            PG_PORT=${{ matrix.stand.pg }} \
            docker compose --project-name ${{ matrix.stand.name }} pull &&
            PROJECT_NAME=${{ matrix.stand.name }} \
            API_PORT=${{ matrix.stand.api }} \
            FRONT_PORT=${{ matrix.stand.front }} \
            PG_PORT=${{ matrix.stand.pg }} \
            docker compose --project-name ${{ matrix.stand.name }} up -d --remove-orphans
          "
