name: Detect Frontend Changes

on:
  workflow_call:

jobs:
  detect_frontend_changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check_frontend.outputs.changed }}

    steps:
      - uses: actions/checkout@v4

      - name: Detect frontend changes
        id: check_frontend
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q "^src/Client/"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
